🐛 Add a broken unit test in 0.24.1
fabiocaccamo/python-benedict pull request #58
Opened 2021-08-03 03:45 UTC by simkimsia

Hi @fabiocaccamo 

The latest 0.24.1 broke something in my Django project.

I did a demo video showing you how I replicated the issue in a unit test. https://www.loom.com/share/1d50cce1764040658d9e9fe4747f9424

This fork also contains my unit test. Please feel free to go through.

Thank you

2021-08-03 14:38 UTC, fabiocaccamo requested changes

2021-08-03 14:38 UTC, fabiocaccamo commented on tests/dicts/test_assign.py
> +            self.assertTrue(True)
How this could fail? :)

2021-08-04 03:10 UTC, simkimsia commented
@fabiocaccamo did you watch my loom? It shows how when I run the same test under 0.24.0 it's fine but when i run 0.24.1 it fails.

2021-08-06 09:17 UTC, simkimsia commented
@fabiocaccamo am i missing something? or u need more info from me? happy to make changes to the unit test to better flesh out the issue

2021-08-08 04:10 UTC, simkimsia commented
I realized that the comment in https://github.com/fabiocaccamo/python-benedict/issues/59#issuecomment-892640386 has the same nature as my issue here. So making a comment to link both together

2021-08-08 05:23 UTC, closed without merging

2021-08-08 05:25 UTC, simkimsia commented
This is deleted after pr #60 is the better solution